apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: ingestion
spec:
  type: LoadBalancer
  selector:
    app: ingestion
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
