apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-layer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      containers:
      - name: analysis
        image: cullm001/analysis-layer:latest
        ports:
        - containerPort: 5001
